all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 34.245.116.176
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/Downloads/Others/gtp-server.pem
        web2:
          ansible_host: 18.201.148.116
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/Downloads/Others/gtp-server.pem
      vars:
        ansible_python_interpreter: /usr/bin/python3